// enterprise-knowledge-base/frontend/src/views/admin/ReviewCenter.vue
<template>
  <div>
    <el-card>
      <h3>审核中心</h3>

      <el-tabs v-model="activeTab">
        <!-- ═══ 待审核文档 ═══ -->
        <el-tab-pane :label="`待审核文档（${docPending.length}）`" name="docs">
          <el-table :data="docPending" stripe v-loading="loadingDoc">
            <el-table-column prop="id" label="ID" width="60" />
            <el-table-column prop="title" label="标题" min-width="200" show-overflow-tooltip />
            <el-table-column prop="scope" label="范围" width="70">
              <template #default="{ row }">{{ scopeLabel(row.scope) }}</template>
            </el-table-column>
            <el-table-column prop="chunk_count" label="切片" width="60" />
            <el-table-column label="操作" width="220">
              <template #default="{ row }">
                <el-button size="small" @click="previewDoc(row.id)">查看</el-button>
                <el-button size="small" type="success" @click="approveDoc(row.id)">通过</el-button>
                <el-button size="small" type="danger" @click="rejectDoc(row.id)">驳回</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <!-- ═══ 已审核文档 ═══ -->
        <el-tab-pane :label="`已审核文档（${docReviewed.length}）`" name="docsReviewed">
          <el-table :data="docReviewed" stripe v-loading="loadingDoc">
            <el-table-column prop="id" label="ID" width="60" />
            <el-table-column prop="title" label="标题" min-width="200" show-overflow-tooltip />
            <el-table-column prop="scope" label="范围" width="70">
              <template #default="{ row }">{{ scopeLabel(row.scope) }}</template>
            </el-table-column>
            <el-table-column label="审核状态" width="100">
              <template #default="{ row }">
                <el-tag :type="row.review_status === 'approved' ? 'success' : 'danger'" size="small">
                  {{ row.review_status === 'approved' ? '已通过' : '已驳回' }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="review_comment" label="审核意见" min-width="150" show-overflow-tooltip />
            <el-table-column label="操作" width="80">
              <template #default="{ row }">
                <el-button size="small" @click="previewDoc(row.id)">查看</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <!-- ═══ 待审核 FAQ ═══ -->
        <el-tab-pane :label="`待审核 FAQ（${faqPending.length}）`" name="faqs">
          <el-table :data="faqPending" stripe v-loading="loadingFaq">
            <el-table-column prop="id" label="ID" width="60" />
            <el-table-column prop="question" label="问题" min-width="250" show-overflow-tooltip />
            <el-table-column prop="scope" label="范围" width="70">
              <template #default="{ row }">{{ scopeLabel(row.scope) }}</template>
            </el-table-column>
            <el-table-column label="操作" width="220">
              <template #default="{ row }">
                <el-button size="small" @click="previewFaq(row)">查看</el-button>
                <el-button size="small" type="success" @click="approveFaq(row.id)">通过</el-button>
                <el-button size="small" type="danger" @click="rejectFaq(row.id)">驳回</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <!-- ═══ 已审核 FAQ ═══ -->
        <el-tab-pane :label="`已审核 FAQ（${faqReviewed.length}）`" name="faqsReviewed">
          <el-table :data="faqReviewed" stripe v-loading="loadingFaq">
            <el-table-column prop="id" label="ID" width="60" />
            <el-table-column prop="question" label="问题" min-width="250" show-overflow-tooltip />
            <el-table-column prop="scope" label="范围" width="70">
              <template #default="{ row }">{{ scopeLabel(row.scope) }}</template>
            </el-table-column>
            <el-table-column label="审核状态" width="100">
              <template #default="{ row }">
                <el-tag :type="row.review_status === 'approved' ? 'success' : 'danger'" size="small">
                  {{ row.review_status === 'approved' ? '已通过' : '已驳回' }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="review_comment" label="审核意见" min-width="150" show-overflow-tooltip />
            <el-table-column label="操作" width="80">
              <template #default="{ row }">
                <el-button size="small" @click="previewFaq(row)">查看</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>
      </el-tabs>
    </el-card>

    <!-- 预览弹窗 -->
    <el-dialog v-model="previewVisible" :title="previewTitle" width="800px" top="5vh">
      <div v-if="previewLoading" style="text-align:center; padding:40px">加载中...</div>
      <div v-else class="preview-body">
        <div v-if="previewType === 'faq'" class="preview-faq">
          <div class="preview-section">
            <div class="preview-label">问题</div>
            <div class="preview-text">{{ previewFaqData?.question }}</div>
          </div>
          <div class="preview-section">
            <div class="preview-label">答案</div>
            <div class="preview-text answer">{{ previewFaqData?.answer }}</div>
          </div>
        </div>
        <div v-else class="preview-doc">
          <div class="preview-section">
            <div class="preview-label">标题</div>
            <div class="preview-text">{{ previewDocData?.title }}</div>
          </div>
          <div class="preview-section">
            <div class="preview-label">正文（{{ previewDocData?.word_count || 0 }} 字）</div>
            <div class="preview-text content">{{ previewDocData?.plain_text || '（无文本内容）' }}</div>
          </div>
        </div>
      </div>
      <template #footer>
        <el-button @click="previewVisible = false">关闭</el-button>
        <template v-if="previewIsPending">
          <el-button type="success" @click="previewApprove">通过</el-button>
          <el-button type="danger" @click="previewReject">驳回</el-button>
        </template>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { fetchDocuments, fetchDocument, reviewDocument, type Document, type DocumentDetail } from "@/api/document";
import { fetchFAQs, approveFAQ, rejectFAQ, type FAQ } from "@/api/faq";

const activeTab = ref("docs");
const loadingDoc = ref(false);
const loadingFaq = ref(false);
const allDocs = ref<Document[]>([]);
const allFaqs = ref<FAQ[]>([]);

const docPending = computed(() => allDocs.value.filter((d) => d.review_status === "pending"));
const docReviewed = computed(() => allDocs.value.filter((d) => d.review_status !== "pending" && d.review_status !== "draft"));
const faqPending = computed(() => allFaqs.value.filter((f) => f.review_status === "pending"));
const faqReviewed = computed(() => allFaqs.value.filter((f) => f.review_status !== "pending" && f.review_status !== "draft"));

// ── 预览弹窗 ──
const previewVisible = ref(false);
const previewLoading = ref(false);
const previewTitle = ref("");
const previewType = ref<"faq" | "doc">("faq");
const previewIsPending = ref(false);
const previewFaqData = ref<FAQ | null>(null);
const previewDocData = ref<DocumentDetail | null>(null);
const previewCurrentId = ref(0);

function scopeLabel(scope: string) {
  if (scope === "public") return "公共";
  if (scope === "customer") return "客服";
  return "内部";
}

async function loadDocs() {
  loadingDoc.value = true;
  try {
    const res = await fetchDocuments({ page_size: 100 });
    allDocs.value = res.items ?? [];
  } catch (e: any) {
    ElMessage.error(e.message || "加载文档列表失败");
  } finally {
    loadingDoc.value = false;
  }
}

async function loadFaqs() {
  loadingFaq.value = true;
  try {
    const res = await fetchFAQs(1, 500);
    allFaqs.value = res.items ?? [];
  } catch (e: any) {
    ElMessage.error(e.message || "加载 FAQ 列表失败");
  } finally {
    loadingFaq.value = false;
  }
}

async function previewFaq(row: FAQ) {
  previewType.value = "faq";
  previewTitle.value = `FAQ 详情 — #${row.id}`;
  previewFaqData.value = row;
  previewDocData.value = null;
  previewCurrentId.value = row.id;
  previewIsPending.value = row.review_status === "pending";
  previewVisible.value = true;
}

async function previewDoc(id: number) {
  previewType.value = "doc";
  previewTitle.value = `文档详情 — #${id}`;
  previewFaqData.value = null;
  previewDocData.value = null;
  previewCurrentId.value = id;
  previewLoading.value = true;
  previewVisible.value = true;
  try {
    const detail = await fetchDocument(id);
    previewDocData.value = detail;
    previewIsPending.value = detail.review_status === "pending";
  } catch (e: any) {
    ElMessage.error(e.message || "加载文档失败");
    previewVisible.value = false;
  } finally {
    previewLoading.value = false;
  }
}

async function previewApprove() {
  const id = previewCurrentId.value;
  if (previewType.value === "doc") {
    await reviewDocument(id, "approve");
    previewVisible.value = false;
    ElMessage.success("已通过");
    await loadDocs();
  } else {
    await approveFAQ(id);
    previewVisible.value = false;
    ElMessage.success("审核通过");
    await loadFaqs();
  }
}

async function previewReject() {
  const id = previewCurrentId.value;
  try {
    const { value } = await ElMessageBox.prompt("请输入驳回原因（选填）", "驳回", {
      confirmButtonText: "确认驳回", cancelButtonText: "取消", inputPlaceholder: "驳回原因...",
    });
    if (previewType.value === "doc") {
      await reviewDocument(id, "reject", value || undefined);
      previewVisible.value = false;
      ElMessage.success("已驳回");
      await loadDocs();
    } else {
      await rejectFAQ(id, value || undefined);
      previewVisible.value = false;
      ElMessage.success("已驳回");
      await loadFaqs();
    }
  } catch { /* cancelled */ }
}

async function approveDoc(id: number) {
  await reviewDocument(id, "approve");
  ElMessage.success("已通过");
  await loadDocs();
}

async function rejectDoc(id: number) {
  try {
    const { value } = await ElMessageBox.prompt("请输入驳回原因（选填）", "驳回文档", {
      confirmButtonText: "确认驳回", cancelButtonText: "取消", inputPlaceholder: "驳回原因...",
    });
    await reviewDocument(id, "reject", value || undefined);
    ElMessage.success("已驳回");
    await loadDocs();
  } catch { /* cancelled */ }
}

async function approveFaq(id: number) {
  try {
    await approveFAQ(id);
    ElMessage.success("审核通过");
    await loadFaqs();
  } catch (e: any) { ElMessage.error(e.message || "操作失败"); }
}

async function rejectFaq(id: number) {
  try {
    const { value } = await ElMessageBox.prompt("请输入驳回原因（选填）", "驳回 FAQ", {
      confirmButtonText: "确认驳回", cancelButtonText: "取消", inputPlaceholder: "驳回原因...",
    });
    await rejectFAQ(id, value || undefined);
    ElMessage.success("已驳回");
    await loadFaqs();
  } catch { /* cancelled */ }
}

onMounted(async () => {
  await Promise.all([loadDocs(), loadFaqs()]);
});
</script>

<style scoped>
.preview-body { max-height: 60vh; overflow-y: auto; }
.preview-section { margin-bottom: 20px; }
.preview-label { font-weight: 600; color: #303133; margin-bottom: 8px; font-size: 14px; }
.preview-text { font-size: 14px; line-height: 1.8; color: #606266; white-space: pre-wrap; word-break: break-word; }
.preview-text.content { background: #f5f7fa; padding: 16px; border-radius: 8px; border: 1px solid #ebeef5; }
.preview-text.answer { background: #f5f7fa; padding: 16px; border-radius: 8px; border: 1px solid #ebeef5; }
</style>

// enterprise-knowledge-base/app/src/pages/console/ReviewCenter.tsx
import { useEffect, useState } from 'react'
import { Loader2, RefreshCw, Eye, Check, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { toast } from 'sonner'
import { getDocuments, getDocument, reviewDocument, type DocumentItem, type DocumentDetail } from '@/api/documents'
import { fetchFAQs, approveFAQ, rejectFAQ, type FAQ } from '@/api/faq'

function scopeLabel(scope: string) {
  if (scope === 'public') return '公共'
  if (scope === 'customer') return '客服'
  return '内部'
}

type PreviewKind = { type: 'doc'; data: DocumentDetail } | { type: 'faq'; data: FAQ } | null

export function ReviewCenter() {
  const [docs, setDocs] = useState<DocumentItem[]>([])
  const [faqs, setFaqs] = useState<FAQ[]>([])
  const [loading, setLoading] = useState(true)
  const [reloadKey, setReloadKey] = useState(0)
  const [preview, setPreview] = useState<PreviewKind>(null)
  const [reject, setReject] = useState<{ type: 'doc' | 'faq'; id: number } | null>(null)
  const [rejectReason, setRejectReason] = useState('')
  const [acting, setActing] = useState(false)

  useEffect(() => {
    let active = true
    Promise.all([
      getDocuments({ page: 1, page_size: 100 }),
      fetchFAQs(1, 500),
    ])
      .then(([d, f]) => { if (active) { setDocs(d.items); setFaqs(f.items) } })
      .catch(() => toast.error('加载审核数据失败'))
      .finally(() => { if (active) setLoading(false) })
    return () => { active = false }
  }, [reloadKey])

  const reload = () => { setLoading(true); setReloadKey(k => k + 1) }

  const docPending = docs.filter(d => d.review_status === 'pending')
  const docReviewed = docs.filter(d => d.review_status !== 'pending' && d.review_status !== 'draft')
  const faqPending = faqs.filter(f => f.review_status === 'pending')
  const faqReviewed = faqs.filter(f => f.review_status !== 'pending' && f.review_status !== 'draft')

  const openDoc = async (id: number) => {
    try { setPreview({ type: 'doc', data: await getDocument(id) }) } catch { toast.error('加载文档失败') }
  }

  const approveDoc = async (id: number) => {
    setActing(true)
    try { await reviewDocument(id, 'approve'); toast.success('已通过'); reload() } catch { toast.error('操作失败') } finally { setActing(false) }
  }

  const confirmReject = async () => {
    if (!reject) return
    setActing(true)
    try {
      if (reject.type === 'doc') await reviewDocument(reject.id, 'reject', rejectReason || undefined)
      else await rejectFAQ(reject.id, rejectReason || undefined)
      toast.success('已驳回')
      setReject(null); setRejectReason(''); setPreview(null); reload()
    } catch { toast.error('操作失败') } finally { setActing(false) }
  }

  const approveFaq = async (id: number) => {
    setActing(true)
    try { await approveFAQ(id); toast.success('审核通过'); reload() } catch { toast.error('操作失败') } finally { setActing(false) }
  }

  if (loading) {
    return <div className="py-24 flex justify-center"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>
  }

  const docTable = (rows: DocumentItem[], reviewed: boolean) => (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-16">ID</TableHead>
          <TableHead>标题</TableHead>
          <TableHead className="w-20">范围</TableHead>
          <TableHead className="w-16">切片</TableHead>
          <TableHead className="w-44 text-right">操作</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map(d => (
          <TableRow key={d.id}>
            <TableCell className="text-sm text-muted-foreground">{d.id}</TableCell>
            <TableCell className="text-sm max-w-md truncate">{d.title}</TableCell>
            <TableCell><Badge variant="outline">{scopeLabel(d.scope)}</Badge></TableCell>
            <TableCell className="text-sm text-muted-foreground">{d.chunk_count}</TableCell>
            <TableCell className="text-right">
              <div className="flex justify-end gap-1">
                <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => openDoc(d.id)}><Eye className="mr-1 h-3 w-3" />查看</Button>
                {!reviewed && (
                  <>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-green-600" disabled={acting} onClick={() => approveDoc(d.id)}><Check className="mr-1 h-3 w-3" />通过</Button>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-destructive" disabled={acting} onClick={() => setReject({ type: 'doc', id: d.id })}><X className="mr-1 h-3 w-3" />驳回</Button>
                  </>
                )}
              </div>
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  )

  const faqTable = (rows: FAQ[], reviewed: boolean) => (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-16">ID</TableHead>
          <TableHead>问题</TableHead>
          <TableHead className="w-20">范围</TableHead>
          <TableHead className="w-44 text-right">操作</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map(f => (
          <TableRow key={f.id}>
            <TableCell className="text-sm text-muted-foreground">{f.id}</TableCell>
            <TableCell className="text-sm max-w-md truncate">{f.question}</TableCell>
            <TableCell><Badge variant="outline">{scopeLabel(f.scope)}</Badge></TableCell>
            <TableCell className="text-right">
              <div className="flex justify-end gap-1">
                <Button variant="ghost" size="sm" className="h-7 text-xs" onClick={() => setPreview({ type: 'faq', data: f })}><Eye className="mr-1 h-3 w-3" />查看</Button>
                {!reviewed && (
                  <>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-green-600" disabled={acting} onClick={() => approveFaq(f.id)}><Check className="mr-1 h-3 w-3" />通过</Button>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-destructive" disabled={acting} onClick={() => setReject({ type: 'faq', id: f.id })}><X className="mr-1 h-3 w-3" />驳回</Button>
                  </>
                )}
              </div>
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  )

  return (
    <div className="p-6 space-y-6 max-w-6xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">审核中心</h1>
          <p className="text-sm text-muted-foreground mt-1">文档与 FAQ 的审核</p>
        </div>
        <Button variant="outline" onClick={reload}><RefreshCw className="mr-2 h-4 w-4" />刷新</Button>
      </div>

      <Tabs defaultValue="docs">
        <TabsList>
          <TabsTrigger value="docs">待审核文档（{docPending.length}）</TabsTrigger>
          <TabsTrigger value="docsReviewed">已审核文档（{docReviewed.length}）</TabsTrigger>
          <TabsTrigger value="faqs">待审核 FAQ（{faqPending.length}）</TabsTrigger>
          <TabsTrigger value="faqsReviewed">已审核 FAQ（{faqReviewed.length}）</TabsTrigger>
        </TabsList>
        <TabsContent value="docs" className="mt-4"><Card><CardContent className="p-0">{docPending.length ? docTable(docPending, false) : <p className="py-12 text-center text-sm text-muted-foreground">无待审核文档</p>}</CardContent></Card></TabsContent>
        <TabsContent value="docsReviewed" className="mt-4"><Card><CardContent className="p-0">{docReviewed.length ? docTable(docReviewed, true) : <p className="py-12 text-center text-sm text-muted-foreground">暂无</p>}</CardContent></Card></TabsContent>
        <TabsContent value="faqs" className="mt-4"><Card><CardContent className="p-0">{faqPending.length ? faqTable(faqPending, false) : <p className="py-12 text-center text-sm text-muted-foreground">无待审核 FAQ</p>}</CardContent></Card></TabsContent>
        <TabsContent value="faqsReviewed" className="mt-4"><Card><CardContent className="p-0">{faqReviewed.length ? faqTable(faqReviewed, true) : <p className="py-12 text-center text-sm text-muted-foreground">暂无</p>}</CardContent></Card></TabsContent>
      </Tabs>

      <Dialog open={!!preview} onOpenChange={open => !open && setPreview(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{preview?.type === 'doc' ? preview.data.title : preview?.type === 'faq' ? 'FAQ 详情' : ''}</DialogTitle>
            <DialogDescription>{preview?.type === 'doc' ? `${preview.data.word_count} 字` : ''}</DialogDescription>
          </DialogHeader>
          {preview?.type === 'faq' && (
            <div className="space-y-3 text-sm">
              <div><div className="font-medium mb-1">问题</div><div>{preview.data.question}</div></div>
              <div><div className="font-medium mb-1">答案</div><div className="whitespace-pre-wrap bg-muted/40 rounded p-3">{preview.data.answer}</div></div>
            </div>
          )}
          {preview?.type === 'doc' && (
            <div className="text-sm whitespace-pre-wrap bg-muted/40 rounded p-3 max-h-[50vh] overflow-y-auto">
              {preview.data.plain_text?.slice(0, 5000) || '（无文本内容）'}
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setPreview(null)}>关闭</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!reject} onOpenChange={open => { if (!open) { setReject(null); setRejectReason('') } }}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>驳回</DialogTitle>
            <DialogDescription>请输入驳回原因（选填）</DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Label>驳回原因</Label>
            <Textarea value={rejectReason} onChange={e => setRejectReason(e.target.value)} className="min-h-[100px]" placeholder="驳回原因..." />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => { setReject(null); setRejectReason('') }}>取消</Button>
            <Button variant="destructive" onClick={confirmReject} disabled={acting}>
              {acting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}确认驳回
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
